version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"   # Vite default port
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:5000  # Frontend calls backend
    command: npm run dev

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env  # Contains MONGO_URI
    volumes:
      - ./backend:/app
      - /app/node_modules